version: '2.1'
services:

  doris_fe:
    image: registry.fit2cloud.com/dataease/doris:0.13
    container_name: doris_fe
    environment:
      - DORIS_ROLE=fe-leader
    volumes:
      - dataease-fe-data:/opt/doris/fe/doris-meta
      - /opt/dataease/conf/fe.conf /opt/doris/fe/conf/fe.conf
    networks:
      dataease-network :
        ipv4_address: 172.19.0.198

  doris_be:
    image: registry.fit2cloud.com/dataease/doris:0.13
    container_name: doris_be
    environment:
      - DORIS_ROLE=be
    volumes:
      - dataease-be-data:/opt/doris/be/storage
      - /opt/dataease/conf/be.conf /opt/doris/be/conf/be.conf
    networks:
      dataease-network :
        ipv4_address: 172.19.0.199

  kettle:
    image: registry.fit2cloud.com/dataease/kettle:8.3
    container_name: kettle
    volumes:
      - /opt/dataease/conf/:/opt/dataease/conf
      - dataease-kettle-data:/opt/dataease/data/kettle
    networks:
      - dataease-network


volumes:
  dataease-fe-data:
    driver_opts:
      type: none
      device: /opt/dataease/data/fe
      o: bind
  dataease-be-data:
    driver_opts:
      type: none
      device: /opt/dataease/data/be
      o: bind
